import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/Components/Header";
import { Footer } from "@/Components/Footer/index.";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "EcoTurismo",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="pt-br" className="overflow-x-hidden">
			<Header />
			<body className={`${inter.className} min-h-screen`}>
				<main className="bg-zinc-100 w-screen min-h-screen h-full pb-60">
					{children}
				</main>
			</body>
			<Footer />
		</html>
	);
}
